import Head from 'next/head'
import Image from 'next/image'
import Topbar from '../components/TopBar'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Topbar />
        <div className="className">
          <p className="text">hello</p>
        </div>
      </div>
    </div>
  )
}

export default Home
